services:
  holywater:
    image: holywater
    container_name: holywater

    depends_on:
      - postgres
      - dynamodb
      - s3
      - redis
    build:
      context: .
      dockerfile: Dockerfile

    command: sleep infinity
    env_file: .env
    volumes:
      - .:/app
    ports:
      - '3000:3000'

  s3:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - PERSISTENCE=1
      - BUCKET_NAME=holywater-content
    ports:
      - '4566:4566'
    volumes:
      - ./scripts/aws:/etc/localstack/init/ready.d
      - s3-data:/var/lib/localstack

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: holywater
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  dynamodb:
    image: localstack/localstack
    ports:
      - '8000:4566'
    environment:
      - SERVICES=dynamodb
      - PERSISTENCE=1
      - TABLE_NAME=Comments
    volumes:
      - ./scripts/aws:/etc/localstack/init/ready.d
      - dynamodb-data:/var/lib/localstack

  redis:
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=secret
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  dynamodb-data:
  s3-data:
  redis-data:
