services:
  holywater:
    image: holywater
    container_name: holywater

    depends_on:
      - postgres
      - dynamodb
      - redis
    build:
      context: .
      dockerfile: Dockerfile

    command: sleep infinity
    env_file: .env
    volumes:
      - .:/app
    ports:
      - '3000:3000'

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: holywater
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  dynamodb:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  redis:
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=secret
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  dynamodb-data:
  redis-data:
